id: TASK-1774607593947-多设备项目选择修复
title: 多设备项目选择修复
status: done
archived: false
created_at: '2026-03-27T10:33:13.948Z'
updated_at: '2026-03-27T11:29:32.118Z'
related_repos: []
depends_on: []
blocked_by: []
tags: []
