id: TASK-1774429979930-项目中文支持
title: 项目中文支持
status: in_progress
archived: false
created_at: '2026-03-25T09:12:59.930Z'
updated_at: '2026-03-25T10:45:56.686Z'
related_repos: []
depends_on: []
blocked_by: []
tags: []
